### ISSUE TITLE
Actividad 4-hernandez Matra Jorge Luis 

### ISSUE THREAD

**Issue by JORGELUIS2266** [SistemasTecTlaxiaco/actividad-4-mapa-mental-JORGELUIS2266#3]
![png_20221005_111952_0000](https://user-images.githubusercontent.com/112587421/194112460-0f7f64c3-afd6-4f52-adf2-3d63c46db7aa.png)

**Comment by josealfredo79** [comment]
Falta calificacion

**Comment by Daisy-GonzalezLita12** [comment]
18 de 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
